# Generated by Django 5.2.7 on 2025-10-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naval_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buques',
        ),
        migrations.DeleteModel(
            name='empresas',
        ),
        migrations.DeleteModel(
            name='planos',
        ),
    ]
