# Generated by Django 5.2.7 on 2025-10-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('naval_app', '0002_delete_buques_delete_empresas_delete_planos'),
    ]

    operations = [
        migrations.CreateModel(
            name='buques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('imo', models.IntegerField(unique=True)),
                ('eslora', models.IntegerField(default=0)),
                ('manga', models.IntegerField(default=0)),
                ('puntal', models.IntegerField(default=0)),
                ('tripulantes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.CharField(max_length=150)),
                ('cuil', models.IntegerField()),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('version', models.IntegerField()),
                ('Autor', models.CharField(max_length=150)),
            ],
        ),
    ]
