# Generated by Django 5.2.7 on 2025-10-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naval_app', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buques',
            new_name='Buque',
        ),
        migrations.RenameModel(
            old_name='empresas',
            new_name='Empresa',
        ),
        migrations.RenameModel(
            old_name='planos',
            new_name='Plano',
        ),
        migrations.RenameField(
            model_name='plano',
            old_name='Autor',
            new_name='autor',
        ),
    ]
